### PR TITLE
Update Armani Sources

### PR DESCRIPTION
**Pull request by TechExhibeo**

### CODE REVIEW

**Comment by Alx31** [comment]
bfq sucks, SIO ftw :p

**Comment by Martinusbe** [comment]
no fighting

**Comment by Alx31** [comment]
lol

**Comment by Martinusbe** [comment]
:8ball:

**Comment by TechExhibeo** [comment]
I need to subscribe for spam fighter naow lol 😂😂😂 
Alex Marty 😘🙋

**Pull request merged**
